import { montserrat, geistSans, geistMono } from "@/components/ui/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navigation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.className}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
